import 'dart:async';
import 'dart:convert';
import 'dart:io';
import 'dart:math';

import 'package:flutter/foundation.dart';

import '../domain/app_log_upload_port.dart';

class HttpsLogUploadConfiguration {
  const HttpsLogUploadConfiguration({
    required this.baseUrl,
    required this.accessToken,
    required this.appId,
    required this.appVersion,
  });

  final String baseUrl;
  final String accessToken;
  final String appId;
  final String appVersion;

  bool get hasRequiredValues {
    return accessToken.isNotEmpty &&
        !RegExp(r'\s').hasMatch(accessToken) &&
        RegExp(r'^[A-Za-z0-9._-]{1,64}$').hasMatch(appId) &&
        appVersion.isNotEmpty &&
        appVersion.length <= 128 &&
        !RegExp(r'[\r\n]').hasMatch(appVersion);
  }
}

abstract final class EvtLogUploadServiceConfiguration {
  static const apiBaseUrlKey = 'EVT_LOG_API_BASE_URL';
  static const uploadTokenKey = 'EVT_LOG_UPLOAD_TOKEN';
  static const appIdKey = 'EVT_LOG_APP_ID';
  static const appVersionKey = 'EVT_LOG_APP_VERSION';

  static const defaultBaseUrl = 'https://log.moreuos.com';

  static const _baseUrl = String.fromEnvironment(
    apiBaseUrlKey,
    defaultValue: defaultBaseUrl,
  );
  static const _accessToken = String.fromEnvironment(uploadTokenKey);
  static const _appId = String.fromEnvironment(
    appIdKey,
    defaultValue: 'aipin_evt',
  );
  static const _appVersion = String.fromEnvironment(
    appVersionKey,
    defaultValue: '0.0.4+5',
  );

  static HttpsLogUploadConfiguration? uploadConfiguration() {
    final configuration = HttpsLogUploadConfiguration(
      baseUrl: _baseUrl.trim(),
      accessToken: _accessToken.trim(),
      appId: _appId.trim(),
      appVersion: _appVersion.trim(),
    );
    return configuration.hasRequiredValues &&
            HttpsAppLogUploadPort.isHttpsBaseUrl(configuration.baseUrl)
        ? configuration
        : null;
  }
}

class HttpsAppLogUploadPort implements AppLogUploadPort {
  HttpsAppLogUploadPort({
    required this.configuration,
    required this.snapshotValidator,
    this.allowInsecureHttpForTesting = false,
    HttpClient Function()? clientFactory,
    DateTime Function()? now,
    String Function()? platform,
    String Function()? requestIdGenerator,
  }) : _clientFactory = clientFactory ?? HttpClient.new,
       _now = now ?? DateTime.now,
       _platform = platform ?? _currentPlatform,
       _requestIdGenerator = requestIdGenerator ?? _newRequestId,
       _baseUri = _parseBaseUri(
         configuration.baseUrl,
         allowInsecureHttpForTesting: allowInsecureHttpForTesting,
       );

  static const maximumFileBytes = 20 * 1024 * 1024;
  static const _connectionTimeout = Duration(seconds: 10);
  static const _requestTimeout = Duration(seconds: 60);
  static final _snapshotFilename = RegExp(
    r'^aipin-\d{4}-\d{2}-\d{2}-\d{2}-\d{2}-\d{2}(?:-\d+)?\.log$',
  );

  final HttpsLogUploadConfiguration configuration;
  final AppLogUploadSnapshotValidator snapshotValidator;
  final bool allowInsecureHttpForTesting;
  final HttpClient Function() _clientFactory;
  final DateTime Function() _now;
  final String Function() _platform;
  final String Function() _requestIdGenerator;
  final Uri _baseUri;

  @override
  bool get isConfigured =>
      kDebugMode &&
      configuration.hasRequiredValues &&
      _isAcceptedBaseUri(
        _baseUri,
        allowInsecureHttpForTesting: allowInsecureHttpForTesting,
      );

  @override
  Future<AppLogUploadReceipt> upload({required String snapshotPath}) async {
    if (!isConfigured) {
      throw const AppLogUploadFailure(AppLogUploadFailureCode.unconfigured);
    }

    final source = File(snapshotPath);
    final filename = source.uri.pathSegments.last;
    if (!_snapshotFilename.hasMatch(filename) ||
        !await snapshotValidator.isTrustedSnapshot(snapshotPath)) {
      throw const AppLogUploadFailure(AppLogUploadFailureCode.invalidSnapshot);
    }

    final bytes = await _snapshotLength(source);
    if (bytes <= 0) {
      throw const AppLogUploadFailure(AppLogUploadFailureCode.invalidSnapshot);
    }
    if (bytes > maximumFileBytes) {
      throw const AppLogUploadFailure(AppLogUploadFailureCode.fileTooLarge);
    }

    final uploadedAt = _now().toUtc();
    final requestId = _requestIdGenerator();
    if (!RegExp(r'^[a-f0-9]{8,32}$').hasMatch(requestId)) {
      throw const AppLogUploadFailure(AppLogUploadFailureCode.invalidSnapshot);
    }
    // The snapshot basename is generated by FileAppLogStore as a readable
    // timestamp (with a numeric same-second sequence when needed). Keep that
    // basename in the multipart request so the server's source filename is
    // time-based as well. The request id remains in the multipart boundary so
    // concurrent requests still get distinct transport boundaries.
    final remoteFilename = filename;
    final boundary = 'evt-log-${uploadedAt.microsecondsSinceEpoch}-$requestId';
    final fields = <List<int>>[
      _fieldBytes(boundary, 'app_id', configuration.appId),
      _fieldBytes(boundary, 'app_version', configuration.appVersion),
      _fieldBytes(boundary, 'platform', _platform()),
      _fieldBytes(boundary, 'uploaded_at', uploadedAt.toIso8601String()),
    ];
    final fileHeader = _fileHeader(boundary, remoteFilename);
    final closingBoundary = utf8.encode('\r\n--$boundary--\r\n');
    final contentLength =
        fields.fold<int>(0, (total, field) => total + field.length) +
        fileHeader.length +
        bytes +
        closingBoundary.length;
    final client = _clientFactory();
    client.connectionTimeout = _connectionTimeout;
    try {
      final request = await _awaitRequest(
        client.postUrl(_baseUri.resolve('/api/v1/diagnostic-logs')),
      );
      request
        ..followRedirects = false
        ..headers.contentType = ContentType(
          'multipart',
          'form-data',
          parameters: <String, String>{'boundary': boundary},
        )
        ..headers.set(
          HttpHeaders.authorizationHeader,
          'Bearer ${configuration.accessToken}',
        )
        ..headers.set(HttpHeaders.acceptHeader, ContentType.json.mimeType)
        ..contentLength = contentLength;
      for (final field in fields) {
        request.add(field);
      }
      request.add(fileHeader);
      await _awaitRequest(request.addStream(source.openRead()));
      request.add(closingBoundary);
      final response = await _awaitRequest(request.close());
      return await _decodeReceipt(response);
    } on AppLogUploadFailure {
      rethrow;
    } on SocketException {
      throw const AppLogUploadFailure(AppLogUploadFailureCode.connection);
    } on HttpException {
      throw const AppLogUploadFailure(AppLogUploadFailureCode.connection);
    } on HandshakeException {
      throw const AppLogUploadFailure(AppLogUploadFailureCode.connection);
    } on TimeoutException {
      throw const AppLogUploadFailure(AppLogUploadFailureCode.timeout);
    } on FileSystemException {
      throw const AppLogUploadFailure(AppLogUploadFailureCode.noSnapshot);
    } finally {
      client.close(force: true);
    }
  }

  Future<int> _snapshotLength(File source) async {
    try {
      if (!await source.exists()) {
        throw const AppLogUploadFailure(AppLogUploadFailureCode.noSnapshot);
      }
      return await source.length();
    } on AppLogUploadFailure {
      rethrow;
    } on FileSystemException {
      throw const AppLogUploadFailure(AppLogUploadFailureCode.noSnapshot);
    }
  }

  Future<AppLogUploadReceipt> _decodeReceipt(
    HttpClientResponse response,
  ) async {
    final raw = await utf8.decodeStream(response);
    Map<String, Object?>? body;
    try {
      final decoded = jsonDecode(raw);
      if (decoded is Map) {
        body = decoded.map<String, Object?>(
          (key, value) => MapEntry(key.toString(), value),
        );
      }
    } on FormatException {
      body = null;
    }

    if (response.statusCode < 200 || response.statusCode >= 300) {
      throw _failureFromResponse(
        code: _nonBlank(body?['code']) ?? _nonBlank(body?['error']),
        statusCode: response.statusCode,
      );
    }

    final id = _nonBlank(body?['id']);
    final status = _nonBlank(body?['status']);
    final receivedAt = _nonBlank(body?['received_at']);
    final receivedBytes = body?['bytes'];
    final sha256 = _nonBlank(body?['sha256']);
    if (id == null ||
        status != 'stored' ||
        receivedAt == null ||
        DateTime.tryParse(receivedAt) == null ||
        receivedBytes is! int ||
        receivedBytes < 0 ||
        sha256 == null) {
      throw const AppLogUploadFailure(AppLogUploadFailureCode.remoteRejected);
    }
    return AppLogUploadReceipt(bytes: receivedBytes);
  }

  AppLogUploadFailure _failureFromResponse({
    required String? code,
    required int statusCode,
  }) {
    final failure = switch (code) {
      'invalid_file' => AppLogUploadFailureCode.invalidSnapshot,
      'file_too_large' => AppLogUploadFailureCode.fileTooLarge,
      'unauthorized' => AppLogUploadFailureCode.authentication,
      'quota_exceeded' ||
      'storage_unavailable' => AppLogUploadFailureCode.remoteRejected,
      _ => switch (statusCode) {
        HttpStatus.unauthorized ||
        HttpStatus.forbidden => AppLogUploadFailureCode.authentication,
        HttpStatus.requestEntityTooLarge =>
          AppLogUploadFailureCode.fileTooLarge,
        >= HttpStatus.internalServerError => AppLogUploadFailureCode.transfer,
        _ => AppLogUploadFailureCode.remoteRejected,
      },
    };
    return AppLogUploadFailure(failure);
  }

  Future<T> _awaitRequest<T>(Future<T> future) =>
      future.timeout(_requestTimeout);

  static bool isHttpsBaseUrl(String value) {
    final uri = Uri.tryParse(value.trim());
    return uri != null && _isAcceptedBaseUri(uri);
  }

  static Uri _parseBaseUri(
    String value, {
    required bool allowInsecureHttpForTesting,
  }) {
    final uri = Uri.tryParse(value.trim());
    if (uri == null ||
        !_isAcceptedBaseUri(
          uri,
          allowInsecureHttpForTesting: allowInsecureHttpForTesting,
        )) {
      throw ArgumentError.value(value, 'baseUrl', '日志服务必须使用 HTTPS 地址。');
    }
    return uri;
  }

  static bool _isAcceptedBaseUri(
    Uri uri, {
    bool allowInsecureHttpForTesting = false,
  }) {
    if (uri.host.isEmpty ||
        uri.userInfo.isNotEmpty ||
        uri.hasQuery ||
        uri.hasFragment) {
      return false;
    }
    final scheme = uri.scheme.toLowerCase();
    return scheme == 'https' ||
        (allowInsecureHttpForTesting &&
            scheme == 'http' &&
            _isLoopback(uri.host));
  }

  static bool _isLoopback(String host) =>
      host == '127.0.0.1' || host == 'localhost' || host == '::1';

  static String _currentPlatform() {
    if (Platform.isAndroid) return 'android';
    if (Platform.isIOS) return 'ios';
    return Platform.operatingSystem;
  }

  static String _newRequestId() {
    final random = Random.secure();
    final buffer = StringBuffer();
    for (var index = 0; index < 16; index += 1) {
      buffer.write(random.nextInt(256).toRadixString(16).padLeft(2, '0'));
    }
    return buffer.toString();
  }

  static List<int> _fieldBytes(String boundary, String name, String value) =>
      utf8.encode(
        '--$boundary\r\n'
        'Content-Disposition: form-data; name="$name"\r\n\r\n'
        '$value\r\n',
      );

  static List<int> _fileHeader(String boundary, String filename) => utf8.encode(
    '--$boundary\r\n'
    'Content-Disposition: form-data; name="file"; filename="$filename"\r\n'
    'Content-Type: text/plain; charset=utf-8\r\n\r\n',
  );

  static String? _nonBlank(Object? value) {
    if (value is! String) return null;
    final result = value.trim();
    return result.isEmpty ? null : result;
  }
}
